### PR TITLE
Cmake feature

### PR DESCRIPTION
**Pull request by EgorWeders**
For rearranged repo

### CODE REVIEW

**Comment by jmattaa** [comment]
What is the need of the CMakeLists.txt file, if the project uses Make as its build system?

**Comment by EgorWeders** [comment]
Cmake is better. It supports more convenient ways to include dirs ( for example : add include paths for libs in plain makefile (need to modify compile flags for each complier) and in cmake you can just add " include_directories()"). Its your choice, what to support, but cmake is standard for crossplatform.

**Comment by EgorWeders** [comment]
I can commit fixes as different commit without cmake

**Comment by jmattaa** [comment]
I will remove the CMakeLists file for now, I believe that there is no need for using CMake right now. Maybe in the future, but I think sticking to Makefiles right now will do it.

**Pull request merged**
